# Generated by Django 4.0.10 on 2023-08-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(default='', max_length=32, unique=True)),
                ('title', models.CharField(default='', max_length=64)),
                ('artists', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('song_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.song')),
            ],
        ),
    ]
