# Generated by Django 4.0.10 on 2023-09-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(default='', max_length=64, unique=True)),
                ('youtube_id', models.CharField(default='', max_length=64, unique=True)),
                ('title', models.CharField(default='', max_length=64)),
                ('artists', models.JSONField()),
                ('chorus_start_ms', models.IntegerField()),
                ('chorus_duration_ms', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='songs',
            name='song_list',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
